import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en';
  static const String _languageKey = 'jayepanah_language';

  LanguageProvider() {
    _loadLanguage();
  }

  String get currentLanguage => _currentLanguage;
  bool get isRTL => _currentLanguage == 'ur';

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_languageKey);
    if (savedLanguage != null && (savedLanguage == 'en' || savedLanguage == 'ur')) {
      _currentLanguage = savedLanguage;
      notifyListeners();
    }
  }

  Future<void> setLanguage(String language) async {
    if (language != 'en' && language != 'ur') return;
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  /// The same string in the other app language (for bilingual captions).
  String tAlternate(String key) {
    final other = _currentLanguage == 'en' ? 'ur' : 'en';
    return _translations[other]?[key] ?? '';
  }

  /// Lookup for a fixed locale (e.g. splash branding: Urdu + English together).
  String tLang(String key, String languageCode) {
    if (languageCode != 'en' && languageCode != 'ur') return t(key);
    return _translations[languageCode]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app.name': 'JayePanah',
      'app.tagline': 'A Place of Calm in Panic',
      'onboarding.what.title': 'What This App Is',
      'onboarding.what.description': 'Immediate support during panic attacks. Quick techniques to help you feel grounded and safe.',
      'onboarding.whatnot.title': 'What This App Is Not',
      'onboarding.whatnot.description': 'This is not therapy. This is not diagnosis. This is first aid for your mind in moments of crisis.',
      'onboarding.privacy.title': 'Privacy & Safety',
      'onboarding.privacy.description': 'Works offline. No personal data required. Your privacy is protected at all times.',
      'onboarding.continue': 'Continue',
      'language.title': 'Choose Your Language',
      'language.subtitle': 'You can change this later in Settings',
      'disclaimer.title': 'Important Information',
      'disclaimer.text': 'JayePanah provides psychological first aid techniques for panic attacks. It is not a substitute for professional mental health care, therapy, or medical diagnosis. It does not replace emergency services. If you are in immediate danger, call your local emergency number or use the Emergency button in the app. For ongoing symptoms or risk to yourself or others, seek qualified professional help.',
      'disclaimer.understand': 'I understand',
      'disclaimer.continue': 'Continue to App',
      'home.title': 'JayePanah',
      'home.subtitle': 'Quick support when you feel overwhelmed',
      'home.self.title': 'I Need Help Now',
      'home.self.subtitle': 'Step-by-step calm when you are panicking',
      'home.helper.title': 'I\'m Helping Someone',
      'home.helper.subtitle': 'Gentle guidance for supporting another person',
      'home.emergency': 'Emergency',
      'home.greeting': 'Welcome — take your time here. When you feel ready, calming guidance is just a tap away.',
      'home.emergency.section': 'Emergency',
      'home.emergency.call_title': 'Emergency call',
      'home.emergency.call_subtitle': 'Your saved number · %s',
      'home.settings': 'Settings',
      'home.learn': 'Learn',
      'home.resume.title': 'Continue previous session?',
      'home.resume.body': 'You have an unfinished calming guide. Pick up where you left off or start fresh.',
      'home.resume.continue': 'Continue',
      'home.resume.restart': 'Start fresh',
      'home.resume.helper.title': 'Continue helper guide?',
      'home.resume.helper.body': 'Your helper steps were paused. Continue from where you stopped or begin again.',
      'flow.home': 'Back to home',
      'settings.title': 'Settings',
      'settings.general': 'General',
      'settings.language': 'Language',
      'settings.textsize': 'Text Size',
      'settings.reducemotion': 'Reduce Motion',
      'settings.appearance': 'Appearance',
      'settings.theme.system': 'Match device',
      'settings.theme.light': 'Light',
      'settings.theme.dark': 'Dark',
      'self.recovery.other': 'Other ways I am feeling',
      'settings.guidance': 'Guidance Preferences',
      'settings.haptic': 'Haptic Breathing',
      'settings.emergency': 'Emergency',
      'settings.emergencynumber': 'Local Emergency Number',
      'settings.trustedcontacts': 'Trusted Contacts',
      'settings.messagetemplate': 'Emergency Message Template',
      'settings.safety': 'Safety & Ethics',
      'settings.datausage': 'Data Usage',
      'settings.anonymous': 'Anonymous Usage',
      'settings.reset': 'Reset App State',
      'settings.about': 'About',
      'settings.purpose': 'Purpose',
      'settings.disclaimer': 'Academic Disclaimer',
      'settings.resources': 'Mental Health Resources',
      'settings.back': 'Back',
      'settings.small': 'Small',
      'settings.medium': 'Medium',
      'settings.large': 'Large',
      'settings.datausage.description': 'This app works offline and does not collect personal information. Anonymous usage data helps improve the app.',
      'settings.reset.description': 'This will clear all your preferences and restart the app.',
      'settings.reset.button': 'Reset Everything',
      'settings.reset.dialog.title': 'Reset settings',
      'settings.reset.dialog.body': 'This clears preferences stored on this device and returns you to the start of the app. Calming sessions in progress will be cleared.',
      'settings.reset.dialog.cancel': 'Cancel',
      'settings.reset.dialog.confirm': 'Reset',
      'settings.contacts.hint': 'Optional: note a name or number you trust (stored only on this device).',
      'settings.message.hint': 'Optional: a short text you can copy if you need to reach out. Stored only on this device.',
      'settings.message.default': 'I need help. I am having a panic attack.',
      'settings.store.privacy': 'JayePanah stores preferences (language, accessibility, optional notes) only on your device. No account is required. This app is not a medical service.',
      'settings.purpose.text': 'JayePanah provides evidence-based grounding techniques for panic attacks. Developed with cultural sensitivity for Pakistan.',
      'settings.disclaimer.text': 'This app is not a replacement for professional mental health care. Always consult qualified professionals for ongoing support.',
      'settings.resources.text': 'Pakistan Mental Health Helpline: 1166\n\nUmang Helpline: 0311-7786264\n\nIf you are in crisis, please reach out to local emergency services.',
      'education.title': 'Understanding Panic',
      'education.back': 'Back',
      'education.section1': 'What is a Panic Attack?',
      'education.section1.text': 'A panic attack is a sudden episode of intense fear or discomfort. It is not dangerous, though it feels overwhelming. Your body is responding to perceived threat—even when you are safe.',
      'education.section2': 'What It Feels Like',
      'education.section2.text': 'Racing heart, shortness of breath, dizziness, feeling unreal, fear of dying. These are normal panic responses. They will pass.',
      'education.section3': 'What Helps',
      'education.section3.text': 'Grounding techniques, slow breathing, gentle movement, calm presence. Avoid telling someone to "just relax"—it doesn\'t help.',
      'education.section4': 'What Makes It Worse',
      'education.section4.text': 'Panic about panic. Avoidance. Isolation. Judgment. These extend suffering.',
      'education.section5': 'How to Support Someone',
      'education.section5.text': 'Stay calm. Speak softly. Offer simple choices. Remind them they are safe. Do not rush them. Be present.',
      'education.section6': 'When to Seek Professional Help',
      'education.section6.text': 'If panic attacks are frequent, disabling, or accompanied by thoughts of self-harm, professional support is essential. This app is first aid—not treatment.',
      'education.section7': 'How This App Helps',
      'education.section7.text': 'JayePanah walks you through stabilization, breathing, grounding, and reassurance—skills drawn from psychological first aid. Open it as soon as you notice panic building; the steps are short and you can repeat them.',
      'education.section8': 'Typical Timeline',
      'education.section8.text': 'Many panic attacks peak within a few minutes, then ease. Feeling shaky, tired, or foggy afterward is common. Rest, drink water, and go gently with yourself.',
      'education.section9': 'When It May Be More Than Panic',
      'education.section9.text': 'Get urgent medical help for severe or crushing chest pain, fainting, breathing trouble that does not improve, confusion, or symptoms that feel completely new. If you are unsure, use Emergency.',
      'education.section10': 'Limits of This App',
      'education.section10.text': 'JayePanah is not therapy or a diagnosis. It does not replace emergency services or a mental health professional. Use crisis lines in Settings when you need human support.',
      'emergency.title': 'Emergency Support',
      'emergency.text': 'You will be connected to local emergency services. Please stay calm. Help is available.',
      'emergency.call': 'Call Emergency Services',
      'emergency.contact_call': 'Call Trusted Contact',
      'emergency.contact_sms': 'Send Message',
      'emergency.no_contact': 'No trusted contact saved',
      'emergency.cancel': 'Cancel',
      'emergency.offline': 'You are offline. Emergency calling may not work. Please find someone nearby if possible.',
      'emergency.call_failed': 'Unable to start the call. Check your device or dial manually.',
      'severity.title': 'How are you feeling?',
      'severity.mild': 'Anxious / uneasy',
      'severity.moderate': 'Panicking / overwhelmed',
      'severity.severe': 'Severe — chest pain or can\'t breathe',
      'severity.mild.sub': 'We\'ll start with breathing techniques',
      'severity.moderate.sub': 'Step-by-step grounding and calm',
      'severity.severe.sub': 'Emergency resources shown first',
      'self.stabilization.title': 'You are safe',
      'self.stabilization.start': 'Start',
      'self.breathing.continue': 'Continue',
      'self.breathing.inhale': 'Breathe In',
      'self.breathing.exhale': 'Breathe Out',
      'self.breathing.count': 'Breaths',
      'self.breathing.semantics': 'Breathing guide. Follow the slow in and out rhythm.',
      'self.breathing.pauseSemantics': 'Pause or resume the breathing animation',
      'self.grounding.see': 'Name 5 things you can see',
      'self.grounding.touch': 'Name 4 things you can touch',
      'self.grounding.hear': 'Name 3 things you can hear',
      'self.grounding.smell': 'Name 2 things you can smell',
      'self.grounding.taste': 'Name 1 thing you can taste',
      'self.grounding.next': 'Next',
      'self.grounding.continue': 'Continue',
      'self.reassurance.1': 'This is uncomfortable, not dangerous.',
      'self.reassurance.2': 'Your body is protecting you.',
      'self.reassurance.3': 'This will pass.',
      'self.reassurance.4': 'Symptoms often peak, then ease. You can ride this wave.',
      'self.reassurance.5': 'You have handled hard moments before. One breath, one step.',
      'self.reassurance.6': 'A frightening thought is not a fact. You can be safe right now.',
      'self.reassurance.next': 'Next',
      'self.reassurance.continue': 'Continue',
      'self.recovery.question': 'How do you feel now?',
      'self.recovery.better': 'Better',
      'self.recovery.same': 'Same',
      'self.recovery.worse': 'Worse',
      'helper.next': 'Next',
      'helper.immediate.title': 'Immediate Response',
      'helper.immediate.stay': 'Stay calm',
      'helper.immediate.with': 'Stay with them',
      'helper.immediate.lower': 'Lower stimulation',
      'helper.communication.title': 'Communication Guide',
      'helper.communication.say': 'What to say',
      'helper.communication.say.text': 'Speak softly. Use simple, reassuring words: "You are safe. I am here with you. This will pass." Offer to breathe slowly together when they are ready—no pressure.',
      'helper.communication.dont': 'What NOT to say',
      'helper.communication.dont.text': 'Avoid "just relax" or "calm down". Do not minimize their experience. Do not rush them.',
      'helper.communication.tone': 'Tone guidance',
      'helper.communication.tone.text': 'Speak slowly and calmly. Use a gentle, steady voice. Match their breathing pace if possible.',
      'helper.breathing.title': 'Breathe together',
      'helper.environmental.title': 'Environmental Control',
      'helper.environmental.noise': 'Reduce noise',
      'helper.environmental.crowd': 'Remove crowd',
      'helper.environmental.sit': 'Sit safely',
      'helper.assessment.title': 'Assessment',
      'helper.assessment.speak': 'Can they speak?',
      'helper.assessment.breathe': 'Can they breathe?',
      'helper.assessment.reducing': 'Is panic reducing?',
      'helper.escalation.title': 'Escalation Decision',
      'helper.escalation.redflags': 'Medical red flags',
      'helper.escalation.redflags.text': 'Chest pain, difficulty breathing, loss of consciousness, or signs of medical emergency require immediate professional help.',
      'helper.escalation.justification': 'When to escalate',
      'helper.escalation.justification.text': 'If symptoms persist, worsen, or if there are any medical concerns, seek professional help immediately. This app provides first aid, not medical treatment.',
      'helper.escalation.emergency': 'Call Emergency',
      'helper.escalation.finish': 'Finish',
    },
    'ur': {
      'app.name': 'جائے پناہ',
      'app.tagline': 'گھبراہٹ میں سکون کی جگہ',
      'onboarding.what.title': 'یہ ایپ کیا ہے',
      'onboarding.what.description': 'گھبراہٹ کے دوران فوری مدد۔ آپ کو پرسکون اور محفوظ محسوس کرنے میں مدد کے لیے آسان طریقے۔',
      'onboarding.whatnot.title': 'یہ ایپ کیا نہیں ہے',
      'onboarding.whatnot.description': 'یہ علاج نہیں ہے۔ یہ تشخیص نہیں ہے۔ یہ بحران کے لمحات میں آپ کے ذہن کے لیے ابتدائی طبی امداد ہے۔',
      'onboarding.privacy.title': 'رازداری اور حفاظت',
      'onboarding.privacy.description': 'آف لائن کام کرتا ہے۔ ذاتی معلومات کی ضرورت نہیں۔ آپ کی رازداری ہر وقت محفوظ ہے۔',
      'onboarding.continue': 'جاری رکھیں',
      'language.title': 'اپنی زبان منتخب کریں',
      'language.subtitle': 'آپ اسے بعد میں ترتیبات میں تبدیل کر سکتے ہیں',
      'disclaimer.title': 'اہم معلومات',
      'disclaimer.text': 'جائے پناہ گھبراہٹ کے حملوں کے لیے نفسیاتی ابتدائی طبی امداد کی تکنیک فراہم کرتا ہے۔ یہ پیشہ ورانہ ذہنی صحت کی دیکھ بھال، تھراپی، یا طبی تشخیص کا متبادل نہیں۔ یہ ہنگامی خدمات کی جگہ نہیں۔ فوری خطرے میں مقامی ہنگامی نمبر پر کال کریں یا ایپ میں ہنگامی بٹن استعمال کریں۔ جاری علامات یا خود یا دوسروں کو نقصان کے خطرے کے لیے قابل اہل پیشہ ور مدد لیں۔',
      'disclaimer.understand': 'میں سمجھتا/سمجھتی ہوں',
      'disclaimer.continue': 'ایپ پر جائیں',
      'home.title': 'جائے پناہ',
      'home.subtitle': 'جب آپ بے حد دباؤ محسوس کریں تو فوری سہارا',
      'home.self.title': 'مجھے ابھی مدد چاہیے',
      'home.self.subtitle': 'گھبراہٹ میں قدم بہ قدم سکون',
      'home.helper.title': 'میں کسی کی مدد کر رہا ہوں',
      'home.helper.subtitle': 'دوسرے شخص کی معاونت کے لیے آسان رہنمائی',
      'home.emergency': 'ہنگامی صورتحال',
      'home.greeting': 'خوش آمدید — یہاں اپنی رفتار سے آگے بڑھیں۔ جب آپ تیار ہوں، آسان رہنمائی ایک تھپتھپاہٹ پر ہے۔',
      'home.emergency.section': 'ہنگام',
      'home.emergency.call_title': 'ہنگامی کال',
      'home.emergency.call_subtitle': 'آپ کا محفوظ نمبر · %s',
      'home.settings': 'ترتیبات',
      'home.learn': 'سیکھیں',
      'home.resume.title': 'پچھلا سیشن جاری رکھیں؟',
      'home.resume.body': 'آپ کی پرسکون کرنے والی رہنمائی ادھوری ہے۔ جہاں چھوڑا تھا وہاں سے شروع کریں یا نئے سرے سے۔',
      'home.resume.continue': 'جاری رکھیں',
      'home.resume.restart': 'نئے سرے سے',
      'home.resume.helper.title': 'مددگار رہنمائی جاری رکھیں؟',
      'home.resume.helper.body': 'آپ کے مددگار مراحل رک گئے تھے۔ وہیں سے جاری کریں یا دوبارہ شروع کریں۔',
      'flow.home': 'ہوم پر واپس',
      'settings.title': 'ترتیبات',
      'settings.general': 'عام',
      'settings.language': 'زبان',
      'settings.textsize': 'متن کا سائز',
      'settings.reducemotion': 'حرکت کم کریں',
      'settings.appearance': 'ظاہری شکل',
      'settings.theme.system': 'آلہ جیسا',
      'settings.theme.light': 'روشن',
      'settings.theme.dark': 'گہرا',
      'self.recovery.other': 'دوسرے احساسات',
      'settings.guidance': 'رہنمائی کی ترجیحات',
      'settings.haptic': 'ہیپٹک سانس لینا',
      'settings.emergency': 'ہنگامی صورتحال',
      'settings.emergencynumber': 'مقامی ہنگامی نمبر',
      'settings.trustedcontacts': 'قابل اعتماد رابطے',
      'settings.messagetemplate': 'ہنگامی پیغام کا سانچہ',
      'settings.safety': 'حفاظت اور اخلاقیات',
      'settings.datausage': 'ڈیٹا کا استعمال',
      'settings.anonymous': 'گمنام استعمال',
      'settings.reset': 'ایپ کی حالت کو دوبارہ ترتیب دیں',
      'settings.about': 'کے بارے میں',
      'settings.purpose': 'مقصد',
      'settings.disclaimer': 'تعلیمی دستبرداری',
      'settings.resources': 'ذہنی صحت کے وسائل',
      'settings.back': 'واپس',
      'settings.small': 'چھوٹا',
      'settings.medium': 'درمیانہ',
      'settings.large': 'بڑا',
      'settings.datausage.description': 'یہ ایپ آف لائن کام کرتی ہے اور ذاتی معلومات جمع نہیں کرتی۔ گمنام استعمال کا ڈیٹا ایپ کو بہتر بنانے میں مدد کرتا ہے۔',
      'settings.reset.description': 'یہ آپ کی تمام ترجیحات کو صاف کر دے گا اور ایپ کو دوبارہ شروع کرے گا۔',
      'settings.reset.button': 'سب کچھ دوبارہ ترتیب دیں',
      'settings.reset.dialog.title': 'ترتیبات دوبارہ ترتیب دیں',
      'settings.reset.dialog.body': 'یہ اس آلہ پر محفوظ ترجیحات صاف کر دے گا اور ایپ کا آغاز دکھائے گا۔ جاری سکون سیشنز بھی صاف ہو جائیں گے۔',
      'settings.reset.dialog.cancel': 'منسوخ',
      'settings.reset.dialog.confirm': 'دوبارہ ترتیب',
      'settings.contacts.hint': 'اختیاری: کسی قابل اعتماد نام یا نمبر کا نوٹ (صرف اس آلہ پر)۔',
      'settings.message.hint': 'اختیاری: مدد کے لیے بھیجنے کے لیے مختصر متن۔ صرف اس آلہ پر محفوظ۔',
      'settings.message.default': 'مجھے مدد چاہیے۔ مجھے گھبراہٹ کا دورہ پڑ رہا ہے۔',
      'settings.store.privacy': 'جائے پناہ صرف آپ کے آلہ پر ترجیحات (زبان، رسائی، اختیاری نوٹس) رکھتا ہے۔ اکاؤنٹ درکار نہیں۔ یہ طبی خدمت نہیں۔',
      'settings.purpose.text': 'جائے پناہ گھبراہٹ کے حملوں کے لیے ثبوت پر مبنی بنیادی تکنیک فراہم کرتا ہے۔ پاکستان کے لیے ثقافتی حساسیت کے ساتھ تیار کیا گیا۔',
      'settings.disclaimer.text': 'یہ ایپ پیشہ ورانہ ذہنی صحت کی دیکھ بھال کا متبادل نہیں ہے۔ جاری مدد کے لیے ہمیشہ قابل اہل پیشہ ور افراد سے مشورہ کریں۔',
      'settings.resources.text': 'پاکستان ذہنی صحت ہیلپ لائن: 1166\n\nامنگ ہیلپ لائن: 0311-7786264\n\nاگر آپ بحران میں ہیں تو براہ کرم مقامی ہنگامی خدمات سے رابطہ کریں۔',
      'education.title': 'گھبراہٹ کو سمجھنا',
      'education.back': 'واپس',
      'education.section1': 'گھبراہٹ کا دورہ کیا ہے؟',
      'education.section1.text': 'گھبراہٹ کا دورہ شدید خوف یا بے چینی کی اچانک قسط ہے۔ یہ خطرناک نہیں ہے، حالانکہ یہ بہت زیادہ محسوس ہوتا ہے۔ آپ کا جسم خطرے کا جواب دے رہا ہے—یہاں تک کہ جب آپ محفوظ ہوں۔',
      'education.section2': 'یہ کیسا محسوس ہوتا ہے',
      'education.section2.text': 'تیز دھڑکن، سانس کی کمی، چکر آنا، غیر حقیقی محسوس کرنا، مرنے کا خوف۔ یہ عام گھبراہٹ کے ردعمل ہیں۔ یہ گزر جائیں گے۔',
      'education.section3': 'کیا مدد کرتا ہے',
      'education.section3.text': 'بنیادی تکنیک، آہستہ سانس لینا، نرم حرکت، پرسکون موجودگی۔ کسی کو "بس آرام کرو" کہنے سے گریز کریں—یہ مدد نہیں کرتا۔',
      'education.section4': 'کیا اسے بدتر بناتا ہے',
      'education.section4.text': 'گھبراہٹ کے بارے میں گھبراہٹ۔ بچنا۔ تنہائی۔ فیصلہ۔ یہ تکلیف کو بڑھاتے ہیں۔',
      'education.section5': 'کسی کی مدد کیسے کریں',
      'education.section5.text': 'پرسکون رہیں۔ آہستہ سے بولیں۔ آسان انتخاب پیش کریں۔ انہیں یاد دلائیں کہ وہ محفوظ ہیں۔ جلدی نہ کریں۔ موجود رہیں۔',
      'education.section6': 'پیشہ ورانہ مدد کب لینی ہے',
      'education.section6.text': 'اگر گھبراہٹ کے دورے بار بار، معذور کن، یا خود کو نقصان پہنچانے کے خیالات کے ساتھ ہیں، تو پیشہ ورانہ مدد ضروری ہے۔ یہ ایپ ابتدائی طبی امداد ہے—علاج نہیں۔',
      'education.section7': 'یہ ایپ کیسے مدد کرتی ہے',
      'education.section7.text': 'جائے پناہ آپ کو مستحکم کرنا، سانس، بنیاد بندی، اور تسلی کے مراحل سے گزارتا ہے—نفسیاتی ابتدائی امداد کے مہارتیں۔ گھبراہٹ بڑھتے ہی کھولیں؛ مراحل مختصر ہیں اور دہرائے جا سکتے ہیں۔',
      'education.section8': 'عام وقت',
      'education.section8.text': 'بہت سے دورے چند منٹ میں بلند ہوتے پھر ہلکے پڑتے ہیں۔ بعد میں کانپنا، تھکاوٹ، یا دھندلاپن عام ہے۔ آرام، پانی، اور اپنے ساتھ نرمی۔',
      'education.section9': 'جب شاید صرف گھبراہٹ نہ ہو',
      'education.section9.text': 'شدید سینے کا درد، بے ہوشی، بہتر نہ ہونے والی سانس کی دشواری، الجھن، یا بالکل نئی علامات پر فوری طبی مدد لیں۔ یقین نہ ہو تو ہنگامی بٹن استعمال کریں۔',
      'education.section10': 'ایپ کی حدود',
      'education.section10.text': 'جائے پناہ تھراپی یا تشخیص نہیں۔ یہ ہنگامی خدمات یا ماہر نفسیات کا متبادل نہیں۔ انسانی مدد کے لیے ترتیبات میں بحران لائنز دیکھیں۔',
      'emergency.title': 'ہنگامی مدد',
      'emergency.text': 'آپ کو مقامی ہنگامی خدمات سے جوڑ دیا جائے گا۔ براہ کرم پرسکون رہیں۔ مدد دستیاب ہے۔',
      'emergency.call': 'ہنگامی خدمات کو کال کریں',
      'emergency.contact_call': 'قابل اعتماد رابطہ کو کال کریں',
      'emergency.contact_sms': 'پیغام بھیجیں',
      'emergency.no_contact': 'کوئی قابل اعتماد رابطہ محفوظ نہیں',
      'emergency.cancel': 'منسوخ کریں',
      'emergency.offline': 'آپ آف لائن ہیں۔ ہنگامی کالنگ کام نہیں کر سکتی۔ اگر ممکن ہو تو قریب کسی کو تلاش کریں۔',
      'emergency.call_failed': 'کال شروع نہیں ہو سکی۔ آلہ چیک کریں یا خود نمبر ملائیں۔',
      'severity.title': 'آپ کیسا محسوس کر رہے ہیں؟',
      'severity.mild': 'فکر مند / بے چین',
      'severity.moderate': 'گھبراہٹ / بے حد دباؤ',
      'severity.severe': 'شدید — سینے میں درد یا سانس نہیں آ رہی',
      'severity.mild.sub': 'ہم سانس لینے کی تکنیک سے شروع کریں گے',
      'severity.moderate.sub': 'قدم بہ قدم بنیادی اور سکون',
      'severity.severe.sub': 'ہنگامی وسائل پہلے دکھائے جائے گے',
      'self.stabilization.title': 'آپ محفوظ ہیں',
      'self.stabilization.start': 'شروع کریں',
      'self.breathing.continue': 'جاری رکھیں',
      'self.breathing.inhale': 'سانس اندر لیں',
      'self.breathing.exhale': 'سانس باہر کریں',
      'self.breathing.count': 'سانسیں',
      'self.breathing.semantics': 'سانس کی رہنمائی۔ آہستہ اندر اور باہر کی رفتار پر چلیں۔',
      'self.breathing.pauseSemantics': 'سانس کی حرکت روکیں یا دوبارہ شروع کریں',
      'self.grounding.see': '5 چیزیں بتائیں جو آپ دیکھ سکتے ہیں',
      'self.grounding.touch': '4 چیزیں بتائیں جو آپ چھو سکتے ہیں',
      'self.grounding.hear': '3 چیزیں بتائیں جو آپ سن سکتے ہیں',
      'self.grounding.smell': '2 چیزیں بتائیں جو آپ سونگھ سکتے ہیں',
      'self.grounding.taste': '1 چیز بتائیں جو آپ چکھ سکتے ہیں',
      'self.grounding.next': 'اگلا',
      'self.grounding.continue': 'جاری رکھیں',
      'self.reassurance.1': 'یہ تکلیف دہ ہے، خطرناک نہیں۔',
      'self.reassurance.2': 'آپ کا جسم آپ کی حفاظت کر رہا ہے۔',
      'self.reassurance.3': 'یہ گزر جائے گا۔',
      'self.reassurance.4': 'علامات اکثر چڑھتی ہیں، پھر ہلکی پڑتی ہیں۔ آپ اس لہر کے ساتھ رہ سکتے ہیں۔',
      'self.reassurance.5': 'آپ نے مشکل لمحات پہلے بھی سہے ہیں۔ ایک سانس، ایک قدم۔',
      'self.reassurance.6': 'خوفناک خیال حقیقت نہیں۔ آپ اب بھی محفوظ ہو سکتے ہیں۔',
      'self.reassurance.next': 'اگلا',
      'self.reassurance.continue': 'جاری رکھیں',
      'self.recovery.question': 'آپ اب کیسا محسوس کر رہے ہیں؟',
      'self.recovery.better': 'بہتر',
      'self.recovery.same': 'ویسا ہی',
      'self.recovery.worse': 'بدتر',
      'helper.next': 'اگلا',
      'helper.immediate.title': 'فوری ردعمل',
      'helper.immediate.stay': 'پرسکون رہیں',
      'helper.immediate.with': 'ان کے ساتھ رہیں',
      'helper.immediate.lower': 'محرکات کم کریں',
      'helper.communication.title': 'مواصلاتی رہنمائی',
      'helper.communication.say': 'کیا کہنا ہے',
      'helper.communication.say.text': 'آہستہ سے بولیں۔ سادہ، تسلی بخش الفاظ: "آپ محفوظ ہیں۔ میں آپ کے ساتھ ہوں۔ یہ گزر جائے گا۔" جب وہ تیار ہوں تو آہستہ سانس ایک ساتھ لینے کی پیشکش کریں—دباؤ نہ ڈالیں۔',
      'helper.communication.dont': 'کیا نہیں کہنا',
      'helper.communication.dont.text': '"بس آرام کرو" یا "پرسکون ہو جاؤ" کہنے سے گریز کریں۔ ان کے تجربے کو کم نہ سمجھیں۔ انہیں جلدی نہ کریں۔',
      'helper.communication.tone': 'لہجے کی رہنمائی',
      'helper.communication.tone.text': 'آہستہ اور پرسکون طریقے سے بولیں۔ نرم، مستحکم آواز استعمال کریں۔ اگر ممکن ہو تو ان کی سانس لینے کی رفتار سے میل کھائیں۔',
      'helper.breathing.title': 'ایک ساتھ سانس لیں',
      'helper.environmental.title': 'ماحولیاتی کنٹرول',
      'helper.environmental.noise': 'شور کم کریں',
      'helper.environmental.crowd': 'ہجوم ہٹائیں',
      'helper.environmental.sit': 'محفوظ طریقے سے بیٹھیں',
      'helper.assessment.title': 'تشخیص',
      'helper.assessment.speak': 'کیا وہ بول سکتے ہیں؟',
      'helper.assessment.breathe': 'کیا وہ سانس لے سکتے ہیں؟',
      'helper.assessment.reducing': 'کیا گھبراہٹ کم ہو رہی ہے؟',
      'helper.escalation.title': 'تشویش کا فیصلہ',
      'helper.escalation.redflags': 'طبی خطرے کی علامات',
      'helper.escalation.redflags.text': 'سینے میں درد، سانس لینے میں دشواری، ہوش کھو جانا، یا طبی ہنگامی صورتحال کی علامات فوری پیشہ ورانہ مدد کی ضرورت ہوتی ہے۔',
      'helper.escalation.justification': 'کب تشویش کریں',
      'helper.escalation.justification.text': 'اگر علامات برقرار رہیں، بدتر ہوں، یا کوئی طبی تشویش ہو تو فوری طور پر پیشہ ورانہ مدد حاصل کریں۔ یہ ایپ ابتدائی طبی امداد فراہم کرتی ہے، علاج نہیں۔',
      'helper.escalation.emergency': 'ہنگامی کال کریں',
      'helper.escalation.finish': 'ختم کریں',
    },
  };
}
