import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en';
  static const String _languageKey = 'jayepanah_language';

  LanguageProvider() {
    _loadLanguage();
  }

  String get currentLanguage => _currentLanguage;
  bool get isRTL => _currentLanguage == 'ur';

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_languageKey);
    if (savedLanguage != null && (savedLanguage == 'en' || savedLanguage == 'ur')) {
      _currentLanguage = savedLanguage;
      notifyListeners();
    }
  }

  Future<void> setLanguage(String language) async {
    if (language != 'en' && language != 'ur') return;
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app.name': 'JayePanah',
      'app.tagline': 'A Place of Calm in Panic',
      'onboarding.what.title': 'What This App Is',
      'onboarding.what.description': 'Immediate support during panic attacks. Quick techniques to help you feel grounded and safe.',
      'onboarding.whatnot.title': 'What This App Is Not',
      'onboarding.whatnot.description': 'This is not therapy. This is not diagnosis. This is first aid for your mind in moments of crisis.',
      'onboarding.privacy.title': 'Privacy & Safety',
      'onboarding.privacy.description': 'Works offline. No personal data required. Your privacy is protected at all times.',
      'onboarding.continue': 'Continue',
      'language.title': 'Choose Your Language',
      'language.subtitle': 'You can change this later in Settings',
      'disclaimer.title': 'Important Information',
      'disclaimer.text': 'JayePanah provides psychological first aid techniques for panic attacks. It is not a substitute for professional mental health care, therapy, or medical diagnosis. If you are in immediate danger, please contact emergency services.',
      'disclaimer.understand': 'I understand',
      'disclaimer.continue': 'Continue to App',
      'home.title': 'JayePanah',
      'home.subtitle': 'Choose how you need help',
      'home.self.title': 'Self-Regulation Mode',
      'home.self.subtitle': 'I am feeling anxious or panicking',
      'home.helper.title': 'Helper Guidance Mode',
      'home.helper.subtitle': 'Someone near me is having a panic attack',
      'home.emergency': 'Emergency',
      'home.settings': 'Settings',
      'home.learn': 'Learn',
      'settings.title': 'Settings',
      'settings.general': 'General',
      'settings.language': 'Language',
      'settings.textsize': 'Text Size',
      'settings.reducemotion': 'Reduce Motion',
      'settings.darkmode': 'Low Stimulus Mode',
      'settings.guidance': 'Guidance Preferences',
      'settings.audio': 'Audio Guidance',
      'settings.voicetype': 'Voice Type',
      'settings.haptic': 'Haptic Breathing',
      'settings.emergency': 'Emergency',
      'settings.emergencynumber': 'Local Emergency Number',
      'settings.trustedcontacts': 'Trusted Contacts',
      'settings.messagetemplate': 'Emergency Message Template',
      'settings.safety': 'Safety & Ethics',
      'settings.datausage': 'Data Usage',
      'settings.anonymous': 'Anonymous Usage',
      'settings.reset': 'Reset App State',
      'settings.about': 'About',
      'settings.purpose': 'Purpose',
      'settings.disclaimer': 'Academic Disclaimer',
      'settings.resources': 'Mental Health Resources',
      'settings.back': 'Back',
      'settings.small': 'Small',
      'settings.medium': 'Medium',
      'settings.large': 'Large',
      'settings.voice.neutral': 'Neutral',
      'settings.voice.human': 'Human',
      'settings.datausage.description': 'This app works offline and does not collect personal information. Anonymous usage data helps improve the app.',
      'settings.reset.description': 'This will clear all your preferences and restart the app.',
      'settings.reset.button': 'Reset Everything',
      'settings.purpose.text': 'JayePanah provides evidence-based grounding techniques for panic attacks. Developed with cultural sensitivity for Pakistan.',
      'settings.disclaimer.text': 'This app is not a replacement for professional mental health care. Always consult qualified professionals for ongoing support.',
      'settings.resources.text': 'Pakistan Mental Health Helpline: 1166\n\nUmang Helpline: 0311-7786264\n\nIf you are in crisis, please reach out to local emergency services.',
      'education.title': 'Understanding Panic',
      'education.back': 'Back',
      'education.section1': 'What is a Panic Attack?',
      'education.section1.text': 'A panic attack is a sudden episode of intense fear or discomfort. It is not dangerous, though it feels overwhelming. Your body is responding to perceived threat—even when you are safe.',
      'education.section2': 'What It Feels Like',
      'education.section2.text': 'Racing heart, shortness of breath, dizziness, feeling unreal, fear of dying. These are normal panic responses. They will pass.',
      'education.section3': 'What Helps',
      'education.section3.text': 'Grounding techniques, slow breathing, gentle movement, calm presence. Avoid telling someone to "just relax"—it doesn\'t help.',
      'education.section4': 'What Makes It Worse',
      'education.section4.text': 'Panic about panic. Avoidance. Isolation. Judgment. These extend suffering.',
      'education.section5': 'How to Support Someone',
      'education.section5.text': 'Stay calm. Speak softly. Offer simple choices. Remind them they are safe. Do not rush them. Be present.',
      'education.section6': 'When to Seek Professional Help',
      'education.section6.text': 'If panic attacks are frequent, disabling, or accompanied by thoughts of self-harm, professional support is essential. This app is first aid—not treatment.',
      'emergency.title': 'Emergency Support',
      'emergency.text': 'You will be connected to local emergency services. Please stay calm. Help is available.',
      'emergency.call': 'Call Emergency Services',
      'emergency.cancel': 'Cancel',
      'emergency.offline': 'You are offline. Emergency calling may not work. Please find someone nearby if possible.',
      'self.stabilization.title': 'You are safe',
      'self.stabilization.start': 'Start',
      'self.breathing.continue': 'Continue',
      'self.breathing.inhale': 'Breathe In',
      'self.breathing.exhale': 'Breathe Out',
      'self.breathing.count': 'Breaths',
      'self.grounding.see': 'Name 5 things you can see',
      'self.grounding.touch': 'Name 4 things you can touch',
      'self.grounding.hear': 'Name 3 things you can hear',
      'self.grounding.smell': 'Name 2 things you can smell',
      'self.grounding.taste': 'Name 1 thing you can taste',
      'self.grounding.next': 'Next',
      'self.grounding.continue': 'Continue',
      'self.reassurance.1': 'This is uncomfortable, not dangerous.',
      'self.reassurance.2': 'Your body is protecting you.',
      'self.reassurance.3': 'This will pass.',
      'self.reassurance.next': 'Next',
      'self.reassurance.continue': 'Continue',
      'self.recovery.question': 'How do you feel now?',
      'self.recovery.better': 'Better',
      'self.recovery.same': 'Same',
      'self.recovery.worse': 'Worse',
      'helper.next': 'Next',
      'helper.immediate.title': 'Immediate Response',
      'helper.immediate.stay': 'Stay calm',
      'helper.immediate.with': 'Stay with them',
      'helper.immediate.lower': 'Lower stimulation',
      'helper.communication.title': 'Communication Guide',
      'helper.communication.say': 'What to say',
      'helper.communication.say.text': 'Speak softly. Use simple, reassuring words. "You are safe. I am here with you. This will pass."',
      'helper.communication.dont': 'What NOT to say',
      'helper.communication.dont.text': 'Avoid "just relax" or "calm down". Do not minimize their experience. Do not rush them.',
      'helper.communication.tone': 'Tone guidance',
      'helper.communication.tone.text': 'Speak slowly and calmly. Use a gentle, steady voice. Match their breathing pace if possible.',
      'helper.breathing.title': 'Breathe together',
      'helper.environmental.title': 'Environmental Control',
      'helper.environmental.noise': 'Reduce noise',
      'helper.environmental.crowd': 'Remove crowd',
      'helper.environmental.sit': 'Sit safely',
      'helper.assessment.title': 'Assessment',
      'helper.assessment.speak': 'Can they speak?',
      'helper.assessment.breathe': 'Can they breathe?',
      'helper.assessment.reducing': 'Is panic reducing?',
      'helper.escalation.title': 'Escalation Decision',
      'helper.escalation.redflags': 'Medical red flags',
      'helper.escalation.redflags.text': 'Chest pain, difficulty breathing, loss of consciousness, or signs of medical emergency require immediate professional help.',
      'helper.escalation.justification': 'When to escalate',
      'helper.escalation.justification.text': 'If symptoms persist, worsen, or if there are any medical concerns, seek professional help immediately. This app provides first aid, not medical treatment.',
      'helper.escalation.emergency': 'Call Emergency',
      'helper.escalation.finish': 'Finish',
    },
    'ur': {
      'app.name': 'جائے پناہ',
      'app.tagline': 'گھبراہٹ میں سکون کی جگہ',
      'onboarding.what.title': 'یہ ایپ کیا ہے',
      'onboarding.what.description': 'گھبراہٹ کے دوران فوری مدد۔ آپ کو پرسکون اور محفوظ محسوس کرنے میں مدد کے لیے آسان طریقے۔',
      'onboarding.whatnot.title': 'یہ ایپ کیا نہیں ہے',
      'onboarding.whatnot.description': 'یہ علاج نہیں ہے۔ یہ تشخیص نہیں ہے۔ یہ بحران کے لمحات میں آپ کے ذہن کے لیے ابتدائی طبی امداد ہے۔',
      'onboarding.privacy.title': 'رازداری اور حفاظت',
      'onboarding.privacy.description': 'آف لائن کام کرتا ہے۔ ذاتی معلومات کی ضرورت نہیں۔ آپ کی رازداری ہر وقت محفوظ ہے۔',
      'onboarding.continue': 'جاری رکھیں',
      'language.title': 'اپنی زبان منتخب کریں',
      'language.subtitle': 'آپ اسے بعد میں ترتیبات میں تبدیل کر سکتے ہیں',
      'disclaimer.title': 'اہم معلومات',
      'disclaimer.text': 'جائے پناہ گھبراہٹ کے حملوں کے لیے نفسیاتی ابتدائی طبی امداد کی تکنیک فراہم کرتا ہے۔ یہ پیشہ ورانہ ذہنی صحت کی دیکھ بھال، تھراپی، یا طبی تشخیص کا متبادل نہیں ہے۔ اگر آپ فوری خطرے میں ہیں تو براہ کرم ہنگامی خدمات سے رابطہ کریں۔',
      'disclaimer.understand': 'میں سمجھتا/سمجھتی ہوں',
      'disclaimer.continue': 'ایپ پر جائیں',
      'home.title': 'جائے پناہ',
      'home.subtitle': 'منتخب کریں کہ آپ کو کس طرح مدد چاہیے',
      'home.self.title': 'خود کو پرسکون کرنے کا طریقہ',
      'home.self.subtitle': 'میں بے چینی یا گھبراہٹ محسوس کر رہا/رہی ہوں',
      'home.helper.title': 'مددگار کی رہنمائی',
      'home.helper.subtitle': 'میرے قریب کسی کو گھبراہٹ کا دورہ پڑ رہا ہے',
      'home.emergency': 'ہنگامی صورتحال',
      'home.settings': 'ترتیبات',
      'home.learn': 'سیکھیں',
      'settings.title': 'ترتیبات',
      'settings.general': 'عام',
      'settings.language': 'زبان',
      'settings.textsize': 'متن کا سائز',
      'settings.reducemotion': 'حرکت کم کریں',
      'settings.darkmode': 'کم محرک موڈ',
      'settings.guidance': 'رہنمائی کی ترجیحات',
      'settings.audio': 'آڈیو رہنمائی',
      'settings.voicetype': 'آواز کی قسم',
      'settings.haptic': 'ہیپٹک سانس لینا',
      'settings.emergency': 'ہنگامی صورتحال',
      'settings.emergencynumber': 'مقامی ہنگامی نمبر',
      'settings.trustedcontacts': 'قابل اعتماد رابطے',
      'settings.messagetemplate': 'ہنگامی پیغام کا سانچہ',
      'settings.safety': 'حفاظت اور اخلاقیات',
      'settings.datausage': 'ڈیٹا کا استعمال',
      'settings.anonymous': 'گمنام استعمال',
      'settings.reset': 'ایپ کی حالت کو دوبارہ ترتیب دیں',
      'settings.about': 'کے بارے میں',
      'settings.purpose': 'مقصد',
      'settings.disclaimer': 'تعلیمی دستبرداری',
      'settings.resources': 'ذہنی صحت کے وسائل',
      'settings.back': 'واپس',
      'settings.small': 'چھوٹا',
      'settings.medium': 'درمیانہ',
      'settings.large': 'بڑا',
      'settings.voice.neutral': 'غیر جانبدار',
      'settings.voice.human': 'انسانی',
      'settings.datausage.description': 'یہ ایپ آف لائن کام کرتی ہے اور ذاتی معلومات جمع نہیں کرتی۔ گمنام استعمال کا ڈیٹا ایپ کو بہتر بنانے میں مدد کرتا ہے۔',
      'settings.reset.description': 'یہ آپ کی تمام ترجیحات کو صاف کر دے گا اور ایپ کو دوبارہ شروع کرے گا۔',
      'settings.reset.button': 'سب کچھ دوبارہ ترتیب دیں',
      'settings.purpose.text': 'جائے پناہ گھبراہٹ کے حملوں کے لیے ثبوت پر مبنی بنیادی تکنیک فراہم کرتا ہے۔ پاکستان کے لیے ثقافتی حساسیت کے ساتھ تیار کیا گیا۔',
      'settings.disclaimer.text': 'یہ ایپ پیشہ ورانہ ذہنی صحت کی دیکھ بھال کا متبادل نہیں ہے۔ جاری مدد کے لیے ہمیشہ قابل اہل پیشہ ور افراد سے مشورہ کریں۔',
      'settings.resources.text': 'پاکستان ذہنی صحت ہیلپ لائن: 1166\n\nامنگ ہیلپ لائن: 0311-7786264\n\nاگر آپ بحران میں ہیں تو براہ کرم مقامی ہنگامی خدمات سے رابطہ کریں۔',
      'education.title': 'گھبراہٹ کو سمجھنا',
      'education.back': 'واپس',
      'education.section1': 'گھبراہٹ کا دورہ کیا ہے؟',
      'education.section1.text': 'گھبراہٹ کا دورہ شدید خوف یا بے چینی کی اچانک قسط ہے۔ یہ خطرناک نہیں ہے، حالانکہ یہ بہت زیادہ محسوس ہوتا ہے۔ آپ کا جسم خطرے کا جواب دے رہا ہے—یہاں تک کہ جب آپ محفوظ ہوں۔',
      'education.section2': 'یہ کیسا محسوس ہوتا ہے',
      'education.section2.text': 'تیز دھڑکن، سانس کی کمی، چکر آنا، غیر حقیقی محسوس کرنا، مرنے کا خوف۔ یہ عام گھبراہٹ کے ردعمل ہیں۔ یہ گزر جائیں گے۔',
      'education.section3': 'کیا مدد کرتا ہے',
      'education.section3.text': 'بنیادی تکنیک، آہستہ سانس لینا، نرم حرکت، پرسکون موجودگی۔ کسی کو "بس آرام کرو" کہنے سے گریز کریں—یہ مدد نہیں کرتا۔',
      'education.section4': 'کیا اسے بدتر بناتا ہے',
      'education.section4.text': 'گھبراہٹ کے بارے میں گھبراہٹ۔ بچنا۔ تنہائی۔ فیصلہ۔ یہ تکلیف کو بڑھاتے ہیں۔',
      'education.section5': 'کسی کی مدد کیسے کریں',
      'education.section5.text': 'پرسکون رہیں۔ آہستہ سے بولیں۔ آسان انتخاب پیش کریں۔ انہیں یاد دلائیں کہ وہ محفوظ ہیں۔ جلدی نہ کریں۔ موجود رہیں۔',
      'education.section6': 'پیشہ ورانہ مدد کب لینی ہے',
      'education.section6.text': 'اگر گھبراہٹ کے دورے بار بار، معذور کن، یا خود کو نقصان پہنچانے کے خیالات کے ساتھ ہیں، تو پیشہ ورانہ مدد ضروری ہے۔ یہ ایپ ابتدائی طبی امداد ہے—علاج نہیں۔',
      'emergency.title': 'ہنگامی مدد',
      'emergency.text': 'آپ کو مقامی ہنگامی خدمات سے جوڑ دیا جائے گا۔ براہ کرم پرسکون رہیں۔ مدد دستیاب ہے۔',
      'emergency.call': 'ہنگامی خدمات کو کال کریں',
      'emergency.cancel': 'منسوخ کریں',
      'emergency.offline': 'آپ آف لائن ہیں۔ ہنگامی کالنگ کام نہیں کر سکتی۔ اگر ممکن ہو تو قریب کسی کو تلاش کریں۔',
      'self.stabilization.title': 'آپ محفوظ ہیں',
      'self.stabilization.start': 'شروع کریں',
      'self.breathing.continue': 'جاری رکھیں',
      'self.breathing.inhale': 'سانس اندر لیں',
      'self.breathing.exhale': 'سانس باہر کریں',
      'self.breathing.count': 'سانسیں',
      'self.grounding.see': '5 چیزیں بتائیں جو آپ دیکھ سکتے ہیں',
      'self.grounding.touch': '4 چیزیں بتائیں جو آپ چھو سکتے ہیں',
      'self.grounding.hear': '3 چیزیں بتائیں جو آپ سن سکتے ہیں',
      'self.grounding.smell': '2 چیزیں بتائیں جو آپ سونگھ سکتے ہیں',
      'self.grounding.taste': '1 چیز بتائیں جو آپ چکھ سکتے ہیں',
      'self.grounding.next': 'اگلا',
      'self.grounding.continue': 'جاری رکھیں',
      'self.reassurance.1': 'یہ تکلیف دہ ہے، خطرناک نہیں۔',
      'self.reassurance.2': 'آپ کا جسم آپ کی حفاظت کر رہا ہے۔',
      'self.reassurance.3': 'یہ گزر جائے گا۔',
      'self.reassurance.next': 'اگلا',
      'self.reassurance.continue': 'جاری رکھیں',
      'self.recovery.question': 'آپ اب کیسا محسوس کر رہے ہیں؟',
      'self.recovery.better': 'بہتر',
      'self.recovery.same': 'ویسا ہی',
      'self.recovery.worse': 'بدتر',
      'helper.next': 'اگلا',
      'helper.immediate.title': 'فوری ردعمل',
      'helper.immediate.stay': 'پرسکون رہیں',
      'helper.immediate.with': 'ان کے ساتھ رہیں',
      'helper.immediate.lower': 'محرکات کم کریں',
      'helper.communication.title': 'مواصلاتی رہنمائی',
      'helper.communication.say': 'کیا کہنا ہے',
      'helper.communication.say.text': 'آہستہ سے بولیں۔ سادہ، تسلی بخش الفاظ استعمال کریں۔ "آپ محفوظ ہیں۔ میں آپ کے ساتھ ہوں۔ یہ گزر جائے گا۔"',
      'helper.communication.dont': 'کیا نہیں کہنا',
      'helper.communication.dont.text': '"بس آرام کرو" یا "پرسکون ہو جاؤ" کہنے سے گریز کریں۔ ان کے تجربے کو کم نہ سمجھیں۔ انہیں جلدی نہ کریں۔',
      'helper.communication.tone': 'لہجے کی رہنمائی',
      'helper.communication.tone.text': 'آہستہ اور پرسکون طریقے سے بولیں۔ نرم، مستحکم آواز استعمال کریں۔ اگر ممکن ہو تو ان کی سانس لینے کی رفتار سے میل کھائیں۔',
      'helper.breathing.title': 'ایک ساتھ سانس لیں',
      'helper.environmental.title': 'ماحولیاتی کنٹرول',
      'helper.environmental.noise': 'شور کم کریں',
      'helper.environmental.crowd': 'ہجوم ہٹائیں',
      'helper.environmental.sit': 'محفوظ طریقے سے بیٹھیں',
      'helper.assessment.title': 'تشخیص',
      'helper.assessment.speak': 'کیا وہ بول سکتے ہیں؟',
      'helper.assessment.breathe': 'کیا وہ سانس لے سکتے ہیں؟',
      'helper.assessment.reducing': 'کیا گھبراہٹ کم ہو رہی ہے؟',
      'helper.escalation.title': 'تشویش کا فیصلہ',
      'helper.escalation.redflags': 'طبی خطرے کی علامات',
      'helper.escalation.redflags.text': 'سینے میں درد، سانس لینے میں دشواری، ہوش کھو جانا، یا طبی ہنگامی صورتحال کی علامات فوری پیشہ ورانہ مدد کی ضرورت ہوتی ہے۔',
      'helper.escalation.justification': 'کب تشویش کریں',
      'helper.escalation.justification.text': 'اگر علامات برقرار رہیں، بدتر ہوں، یا کوئی طبی تشویش ہو تو فوری طور پر پیشہ ورانہ مدد حاصل کریں۔ یہ ایپ ابتدائی طبی امداد فراہم کرتی ہے، علاج نہیں۔',
      'helper.escalation.emergency': 'ہنگامی کال کریں',
      'helper.escalation.finish': 'ختم کریں',
    },
  };
}
